[package]
name = "RookTAB"
version = "0.1.0"
edition = "2024"
authors = ["xRookieFight"]
license = "MIT"
description = "Tab list header, footer, name formatting and sorting plugin for PumpkinMC."

[lib]
name = "rooktab"
crate-type = ["cdylib"]

[dependencies]
pumpkin-plugin-api = { version = "0.1.0", git = "https://github.com/Pumpkin-MC/Pumpkin", package = "pumpkin-plugin-api" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"

[profile.release]
lto = true
opt-level = "s"
strip = true
